project_id = "xdjvlcelauvibznnbrzb"

[functions.sgt-webhook]
verify_jwt = false

[functions.cadence-runner]
verify_jwt = false

[functions.tokeniza-offers]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false
